### ISSUE TITLE
Gerenciamento do Firebase 

### ISSUE THREAD

**Issue by JoaoLSouto** [JoaoLSouto/Fase-III#1]

**Comment by rv-lucas** [comment]
A primeira etapa a realizar nesta fase 3 é configurar o firebase para ficar vinculado na plataforma de programação online Expo.
Após selecionar o nome do projeto, será necessário configurar o Cloud FireStore afim de criar um banco de dados para salvar os dados, no caso do nosso aplicativo, os dados de email e senha dos usuários.
Para finalizar, vamos criar uma coleção (um "sub" banco de dados) para armazenar seus devidos tipos de dados. Após isso, será necessário adicionar ID dos documentos neste banco, para individualizar cada valor em seu devido usuário, como no exemplo abaixo:
