### ISSUE TITLE
Firebase: salvando os cadastros de usuário.

### ISSUE THREAD

**Issue by JoaoLSouto** [JoaoLSouto/Fase-III#2]

**Comment by Rafaellvna** [comment]
Criamos um Documento para criar funções com o objetivo de registrar os dados dos novos usuários, criando constantes e status para a entrada e saída do e-mail e senha,  como mostrado na imagem abaixo:
![image](https://user-images.githubusercontent.com/102112081/176044483-60ce667c-acbc-4d84-ae90-0572cba00844.png)

**Comment by gabriel85739306** [comment]
Após isso, em seguida iremos criar funções de retorno para os valores do e-mail e da senha, após isso, vamos exportar este código para os outros documentos do aplicativo.
![WhatsApp Image 2022-06-27 at 18 59 18](https://user-images.githubusercontent.com/101371616/176045081-216b026d-6738-4ce3-aadc-ba7ce8152e0d.jpeg)

**Comment by matusa17** [comment]
Após as configurações no Context e criando o documento com as funções de registro de dados e exporta-los para os restante do aplicativo, vamos implementar os botões com funções de registro de dados e status de logado assim que forem pressionados.
![beb35931-2b27-4b95-9728-26a3bb30198a](https://user-images.githubusercontent.com/102109777/176045945-3ebdd09c-e126-4f91-b85c-615fe126be25.jpg)
